[profile.default]
# Compilation
solc_version = "0.8.13"
optimizer = true
optimizer_runs = 8000
deny_warnings = true

# Testing
gas_reports = ["*"]
verbosity = 1
chain_id = 99
libs = ["lib"]

[profile.ci]
verbosity = 4
